website/views.py
##PARA CORRER O PROGRAMA python3 main.py

from time import sleep
from datetime import datetime
from time import sleep
from docx import Document
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, send_file
from . import views
from .data_base import *
import os, shutil, zipfile, re

views = Blueprint("views", __name__)

#TURMAS
@views.route("/turmas", methods=["GET", "POST"])
def turmas():
    turmasData = session.query(Turmas).all()
    return render_template("turmas.html", turmasData=turmasData)

@views.route("/criar_turma", methods=["GET", "POST"])
def criar_turma():
    if request.method == "POST":
        turma = request.form["turma"]
        turmaInserir = Turmas(descricao=turma)
        turma = session.query(Turmas).filter_by(descricao=turma).first()
        arr = []
        if turma == None:
            arr.append(0)
            session.add(turmaInserir)
            session.commit()
        else:
            arr.append("Turma já criada")
        return jsonify(arr)
    return render_template("criar_turma.html")

@views.route("/editar_turma/<int:id>", methods=["GET", "POST"])
def editar_turma(id):
    if request.method == "POST":
        turma_desc = request.form["turma"]
        turma = session.query(Turmas).filter_by(descricao=turma_desc).first()
        turma_antiga = session.query(Turmas).filter_by(id=id).first()
        arr = []
        if turma != None:
            if turma.descricao == turma_antiga.descricao:
                arr.append("Não pode alterar o nome da turma para o mesmo nome")
                return jsonify(arr)
        if turma == None:
            arr.append(0)
            turma_antiga.descricao = turma_desc
            session.commit()
        else:
            arr.append("Já existe uma turma com o mesmo nome")
        return jsonify(arr)
    turmaEditar = session.query(Turmas).get(id)
    if turmaEditar == None:
        return redirect(url_for("views.turmas"))
    return render_template("editar_turma.html", turmaEditar=turmaEditar, id=id)

@views.route("/eliminar_turma/<int:id>", methods=["GET", "POST"])
def eliminar_turma(id):
    turma = session.query(Turmas).filter_by(id=id).first()
    if turma == None:
        return redirect(url_for("views.turmas"))
    session.delete(turma)
    session.commit()
    return redirect(url_for("views.turmas"))

#ALUNOS
@views.route("/alunos", methods=["GET", "POST"])
def alunos():
    turmasData = session.query(Turmas).all()
    return render_template("alunos.html", turmasData=turmasData)

@views.route("/criar_aluno", methods=["GET", "POST"])
def criar_aluno():
    turmasData = session.query(Turmas).all()
    if request.method == "POST":
        nif = request.form["nif"]
        nr = request.form["numero"]
        turmaDesc = request.form["inputTurma"]
        turma = session.query(Turmas).filter_by(descricao=turmaDesc).first()
        turma_id = turma.id
        nome = request.form["nome"]
        nome_split = nome.split()
        nome_abreviado = nome_split[0] + " " + nome_split[-1]
        adress = request.form["morada"]
        codPostal = request.form["codpostal"]
        localidade = request.form["local"]
        codPostal = codPostal + " " + localidade
        validade = request.form["validade"]
        cc = request.form["cc"]
        alunoInserir = Alunos(nif=nif,nr=nr,turmaId=turma_id,nome=nome,morada=adress,cod_postal=codPostal,validade_cc=validade,cartao_cidadao=cc,nome_abreviado=nome_abreviado,)
        arr = []
        if session.query(Alunos).filter_by(turmaId=turma_id, nr=nr).first() is None:
            if session.query(Alunos).filter_by( nif=nif).first() is None:
                if session.query(Alunos).filter_by(cartao_cidadao=cc).first() is None:
                    pass
                else:    
                    arr.append("Já existe um aluno com o mesmo CC")
            else:
                arr.append("Já existe um aluno com o mesmo NIF")
        else:
            arr.append( "Aluno com o mesmo número já criado")
        
        if len(arr) != 0:
            pass
        else:
            arr.append(0)
            session.add(alunoInserir)        
            session.commit()
        return jsonify(arr), 200
    return render_template("criar_aluno.html", turmasData = turmasData)

@views.route("/editar_aluno/<int:id>", methods=["GET", "POST"])
def editar_aluno(id):
    if request.method == "POST":
        aluno = session.query(Alunos).filter_by(id=id).first()
        nif = request.form["nif"]
        nr = request.form["numero"]
        turmaId = request.form["inputTurma"]
        turma = session.query(Turmas).filter_by(id=turmaId).first()
        turma_id = turma.id
        nome = request.form["nome"]
        nome_split = nome.split()
        nome_abreviado = nome_split[0] + " " + nome_split[-1]
        adress = request.form["morada"]
        codPostal = request.form["codpostal"]
        localidade = request.form["local"]
        codPostal = codPostal + " " + localidade
        validade = request.form["validade"]
        cc = request.form["cc"]
        arr = []
        nraluno = session.query(Alunos).filter_by(turmaId=turma_id, nr=nr).first()
        nifaluno = session.query(Alunos).filter_by( nif=nif).first()
        ccaluno = session.query(Alunos).filter_by(cartao_cidadao=cc).first()
        if nraluno is None:
            pass
        else:
            if(nraluno.id != id):
                arr.append( "Aluno com o mesmo número já criado")
        if nifaluno is None:
            pass
        else:
            if(nifaluno.id != id):
                arr.append("Já existe um aluno com o mesmo NIF")
        if ccaluno is None:
            pass
        else:
            if(ccaluno.id != id):
                arr.append( "Aluno com o mesmo cc já criado")

        if len(arr) != 0:
            pass
        else:
            arr.append(0)
            aluno.nif = nif
            aluno.nr = nr
            aluno.turmaId = turma_id
            aluno.nome = nome 
            aluno.nome_abreviado = nome_abreviado
            aluno.morada = adress
            aluno.cod_postal = codPostal
            aluno.localidade = localidade
            aluno.validade_cc = validade
            aluno.cartao_cidao = cc
            session.commit()
        return jsonify(arr), 200
    turmasData = session.query(Turmas).all()
    alunoEditar = session.query(Alunos).get(id)
    if alunoEditar == None:
        return redirect(url_for("views.alunos"))
    localidade = alunoEditar.cod_postal[8:].strip()
    print(localidade)
    alunoEditar.cod_postal = alunoEditar.cod_postal[:8]
    return render_template("editar_aluno.html", alunoEditar=alunoEditar, id=id, turmasData=turmasData, localidade = localidade)

@views.route("/eliminar_aluno/<int:id>", methods=["GET", "POST"])
def eliminar_aluno(id):
    aluno = session.query(Alunos).filter_by(id=id).first()
    if aluno is None:
        return redirect(url_for("views.alunos"))
    session.delete(aluno)
    session.commit()
    return redirect(url_for("views.alunos"))






#ENTIDADES
@views.route("/entidades")
def entidades():
    entidadesData = session.query(Entidade).all()
    return render_template("entidades.html", entidadesData=entidadesData)
@views.route("/criar_entidade", methods=["GET", "POST"])
def criar_entidade():
    if request.method == "POST":
        nif = request.form["nif"]
        nome = request.form["nome"]
        adress = request.form["morada"]
        codPostal = request.form["cod_postal"]
        pessoa_responsavel = request.form["pessoa_responsavel"]
        cargo_responsavel = request.form["cargo_responsavel"]
        localidade = request.form["localidade"]
        codPostal = codPostal + " " + localidade
        entidades = Entidade(nif=nif,nome=nome,morada=adress,cod_postal=codPostal,cargo_pessoa_responsavel=cargo_responsavel,pessoa_responsavel=pessoa_responsavel,)
        arr = []
        if session.query(Entidade).filter_by(nif = nif).first() is None:
            if session.query(Entidade).filter_by(nome = nome).first() is None:
                pass
            else:
                arr.append("Entidade com o mesmo nome já adicionada")
        else:
                arr.append("Entidade com o mesmo NIF já adicionada")
        if len(arr) != 0:
            pass
        else:
            arr.append(0)
            session.add(entidades)
            session.commit()    
        return jsonify(arr), 200
    return render_template("criar_entidade.html")

@views.route("/editar_entidade/<int:id>", methods=["GET", "POST"])
def editar_entidade(id):
    if request.method == "POST":
        entidade = session.query(Entidade).filter_by(id=id).first()
        nif = request.form["nif"]
        nome = request.form["nome"]
        morada = request.form["morada"]
        cod_postal = request.form["cod_postal"]
        pessoa_responsavel = request.form["pessoa_responsavel"]
        cargo_pessoa_responsavel = request.form["cargo_responsavel"]
        localidade = request.form["localidade"]
        cod_postal = cod_postal + " " + localidade
        arr = []
        nifEntidade = session.query(Entidade).filter_by(nif = nif).first()
        nomeEntidade = session.query(Entidade).filter_by(nome = nome).first()
        if nifEntidade is None:
            pass
        else:
            if nifEntidade.id != id:
                arr.append( "Entidade com o mesmo nif já adicionada")
        if nomeEntidade is None:
            pass
        else: 
            if nomeEntidade.id != id:
                arr.append("Entidade já com o mesmo nome criada")
                
        if len(arr) != 0:
            pass
        else:
            arr.append(0)
            entidade.nif = nif
            entidade.nome = nome
            entidade.morada = morada
            entidade.cod_postal = cod_postal
            entidade.pessoa_responsavel = pessoa_responsavel
            entidade.cargo_pessoa_responsavel = cargo_pessoa_responsavel
            session.commit()   

website/templates/alunos.html
{% extends 'base.html' %}

{% block main %}
{% if turmasData | length == 0 %}
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Alunos</h1>
  <div class="d-flex justify-content-center">
    <p style="color: red; font-size: 17px">Não existem turmas para criar alunos</p>
  </div>
  <a href="{{url_for('views.criar_turma')}}">
    <button type="button" class="btn btn-primary">Nova turma</button>
  </a>
</div>
{% else %}
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Alunos</h1>
</div>
<table class="table table-sm" align="center" style="width: 1100px; max-width: 1100px" id="table">
  <thead>
    <th style="float: left; border: none; margin-top: 6px">
      <label for="inputTurma" class="form-label" aria-label="Default select example">Turma:</label>
      <select id="inputTurma" class="form-select form-select-lg">
        {% for row in turmasData %}
        <option value="{{row.id}}">{{row.descricao}}</option>
        {% endfor %}
      </select>
    </th>
    <th id style="float: left; border: none; margin-bottom: 20px;">
      <a href="/criar_aluno">
        <button type="button" class="btn btn-primary">Novo Aluno</button>
      </a>
    </th>
  </thead>
  <thead id="thead1">
    <tr>
      <th scope="col">Numero</th>
      <th scope="col">Nome Abreviado</th>
      <th scope="col">Nome</th>
      <th scope="col">Morada</th>
      <th scope="col">Cód.Postal</th>
      <th scope="col">Número CC</th>
      <th scope="col">Nif</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id="tbody">
  </tbody>
  <tbody style="border: none;" id="div1">
    <tr style="border: none;">
      <td style="border: none; display: 'none';">
        <p style="text-align: center; color: red; font-size: 17px">Turma sem alunos</p>
      </td>
    </tr>
  </tbody>
</table>

<script>
  $(document).ready(function () {
    let turmaSelecionada = $("#inputTurma").val();
    carregar_alunos(turmaSelecionada);
  });

  $('#inputTurma').on('change', function () {
    var turmaSelecionada = $(this).val();
    carregar_alunos(turmaSelecionada);
  });

  function carregar_alunos(turmaSelecionada) {
    $.ajax({
      url: "/get_alunos",
      type: "POST",
      data: JSON.stringify({
        "turmaSelecionada": turmaSelecionada
      }),
      contentType: "application/json",
      success: function (response) {
        updateTable(response);
        const tableBody = document.getElementById("tbody");
        const div1 = document.getElementById("div1");
        const thead = document.getElementById("thead1");
        if (tableBody.children.length === 0) {
          div1.style.display = '';
          thead.style.display = 'none';
        } else {
          thead.style.display = '';
          div1.style.display = 'none';
        }
      },
      error: function (xhr, status, error) {
        console.error(error);
      }
    });
  }

  function updateTable(response) {
    alunos = response;
    const tableBody = document.getElementById("tbody");
    const div1 = document.getElementById("div1");

    tableBody.innerHTML = "";

    alunos.forEach((aluno) => {
      let id = aluno.id;
      let url_editar = "{{url_for('views.editar_aluno', id=123)}}".replace("123", id);
      let textEdit = `
        </th>
        <th id="table-button" class="table-button" scope="col">
          <a href="${url_editar}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
            </svg>
          </a>
        </th>`;
      let url_del = "{{url_for('views.eliminar_aluno', id=123)}}".replace("123", id);
      let textDel = `
        <th id="table-button" class="table-button" scope="col">
          <a href="${url_del}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
            </svg>
          </a>
        </th>`;

      const row = tableBody.insertRow();
      const cellNumero = row.insertCell(0);
      cellNumero.width = "120px";
      const cellNomeAbreviado = row.insertCell(1);
      const cellNome = row.insertCell(2);
      const cellMorada = row.insertCell(3);
      const cellCodPostal = row.insertCell(4);
      const cellCartaoCidadao = row.insertCell(5);
      const cellNif = row.insertCell(6);
      const cellEdit = row.insertCell(7);
      const cellDel = row.insertCell(8);

      cellNumero.innerText = aluno.nr;

      cellNomeAbreviado.innerText = aluno.nome_abreviado;
      cellNome.innerText = aluno.nome;
      cellMorada.innerText = aluno.morada;
      cellCodPostal.innerText = aluno.cod_postal;
      cellCartaoCidadao.innerText = aluno.cartao_cidadao;
      cellNif.innerText = aluno.nif;
      cellEdit.innerHTML = textEdit;
      cellDel.innerHTML = textDel;
    });
  }
</script>
{% endif %}
{% endblock %}

website/templates/criar_aluno.html
{% extends 'base.html' %}

{% block main %}
{% if turmasData %}
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Criar Aluno</h1>
</div>
<div class="d-flex justify-content-center" style="margin-top: 50px">
  <form action="{{url_for('views.criar_aluno')}}" class="row g-3" style="margin-top: 50px; width: 600px" id="myForm"
    method="post">
    <div class="col-md-11 text-center" style="margin-left: 17px">
      <label for="inputTurma" class="form-label" aria-label="Default select example">Turma</label>
      <select name="inputTurma" id="inputTurma" class="form-select form-select-lg">
        {% for row in turmasData %}
        <option>{{ row.descricao }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col-3">
      <label class="form-label">Número</label>
      <input name="numero" type="number" min="1" class="form-control" id="numero" placeholder="Número" required>
    </div>
    <div class="col-9">
      <label class="form-label">Nome</label>
      <input name="nome" type="text" class="form-control" id="nome" placeholder="Nome" required>
    </div>
    <div class="col-6" style="margin-top: 5px">
      <label class="form-label">Morada</label>
      <input name="morada" type="text" class="form-control" id="morada" placeholder="Rua, Prédio, Andar" required>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label class="form-label">Cód.Postal</label>
      <input name="codpostal" maxlength="8" type="text" class="form-control" id="postal-code-input"
        placeholder="Cod.Postal" required>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label class="form-label">Localidade</label>
      <input name="local" type="text" class="form-control" id="localidade" placeholder="Localidade" required>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label class="form-label">Cartão Cidadão</label>
      <input name="cc" type="text" maxlength="8" class=" form-control" id="cc" required>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label class="form-label">Nif</label>
      <input name="nif" maxlength="9" type="text" min="0" class="form-control" id="nif" required>
    </div>
    <div class="col-md-4" style="margin-top: 5px">
      <label class="form-label">Validade CC</label>
      <input name="validade" type="date" class="form-control" id="validade" required>
    </div>
    <div class="col-md-2" style="margin-top: 37px; padding-left: 9px">
      <button type="submit" value="submit" class="btn btn-primary">Gravar</button>
    </div>
  </form>
</div>
{% else %}
<div class="d-flex justify-content-center" style="margin-top: 50px">
  <form class="row g-3" style="margin-top: 50px; width: 600px">
    <div class="col-md-11 text-center" style="margin-left: 17px">
      <label for="inputTurma" class="form-label" aria-label="Default select example">Nenhuma turma encontrada</label>
      <a href="{{url_for('views.criar_turma')}}">
        <label for="inputTurma" class="form-label" aria-label="Default select example">crie aqui</label>
      </a>
    </div>
    <div class="col-2">
      <label for="inputNumero" class="form-label">Número</label>
      <input name="numero" type="text" min="1" class="form-control" id="inputNumero" disabled>
    </div>
    <div class="col-5">
      <label for="inputNome" class="form-label">Nome</label>
      <input name="nome" type="text" class="form-control" id="inputNome" disabled>
    </div>
    <div class="col-9" style="margin-top: 5px">
      <label for="inputAddress2" class="form-label">Morada</label>
      <input name="morada" type="text" class="form-control" id="inputAddress2" placeholder="Rua, Prédio, Andar"
        disabled>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label for="inputCodPostal" class="form-label">Cód.Postal</label>
      <input name="codpostal" type="text" class="form-control" id="inputCodPostal" disabled>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label for="inputCC" class="form-label">Cartão Cidadão</label>
      <input name="cc" type="text" min="000000000" class="form-control" id="inputCC" disabled>
    </div>
    <div class="col-md-3" style="margin-top: 5px">
      <label for="inputNif" class="form-label">Nif</label>
      <input name="nif" type="text" min="0" class="form-control" id="inputNif" disabled>
    </div>
    <div class="col-md-4" style="margin-top: 5px">
      <label for="inputValidade" class="form-label">Validade CC</label>
      <input name="validade" type="date" class="form-control" id="inputValidade" disabled>
    </div>
    <div class="col-md-2" style="margin-top: 37px; padding-left: 9px">
      <button type="submit" value="submit" class="btn btn-primary">Gravar</button>
    </div>
  </form>
</div>
{% endif %}

<script>
  $(document).ready(function () {
    $('#myForm').submit(function (event) {
      event.preventDefault();
      var formData = $(this).serialize();
      $.ajax({
        type: 'POST',
        url: '/criar_aluno',
        data: formData,
        success: function (response) {
          if (response[0] === 0) {
            window.location.href = "{{ url_for('views.alunos') }}";
          } else {
            Toastify({
              text: response[0],
              duration: 2500,
              position: "center",
            }).showToast();
          }
        },
        error: function (error) {
          console.log(error);
        }
      });
    });
  });
  const numeroInput = document.getElementById('numero');
  numeroInput.addEventListener('input', function (event) {
    const input = event.target;
    const value = input.value;
    const newValue = value.replace(/\D/g, '');
    input.value = newValue;
  });



  const nifInput = document.getElementById('nif');
  nifInput.addEventListener('input', function (event) {
    const input = event.target;
    const value = input.value;
    const newValue = value.replace(/\D/g, '');
    input.value = newValue;
  });
  const codigoPostalInput = document.getElementById('postal-code-input');
  codigoPostalInput.addEventListener('input', function (event) {
    const input = event.target;
    const value = input.value;
    const cleanedValue = value.replace(/\D/g, '');
    let formattedValue = cleanedValue;
    if (cleanedValue.length > 4) {
      formattedValue = cleanedValue.slice(0, 4) + '-' + cleanedValue.slice(4);
    }
    input.value = formattedValue;
  });

  const LocalidadeInput = document.getElementById('localidade');
  LocalidadeInput.addEventListener('input', function (event) {
    const input = event.target;
    const value = input.value;
    const newValue = value.replace(/[^a-zA-Z\s]/g, '');
    input.value = newValue;
  })

  const cc = document.getElementById('cc');
  cc.addEventListener('input', function (event) {
    const input = event.target;
    const value = input.value;
    const newValue = value.replace(/\D/g, '');
    input.value = newValue;
  });
</script>



{% endblock %}

website/templates/turmas.html
{% extends 'base.html' %}

{% block css %}
<style>
    .table#td1 {
        padding-left: 8px;
    }

    .table td {
        max-width: 30px;
    }

    #table-button {
        width: 25px;
        text-align: right;
    }

    #divbtn {
        margin-right: 300px;
    }

    @media (min-width: 992px) {
        .rounded-lg-3 {
            border-radius: 0.3rem;
        }

        #sapn {
            font-size: 12px;
            margin: 3px 0 0 1px;
            color: red;
        }
    }
</style>
{% endblock %}

{% block main %}
{% if turmasData | length == 0 %}
<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Turmas</h1>
    <div class="d-flex justify-content-center">
        <p style="color: red; font-size: 17px">Não existem Turmas</p>
    </div>
    <a href="{{url_for('views.criar_turma')}}">
        <button type="button" class="btn btn-primary">Nova Turma</button>
    </a>
</div>
{% else %}
<div class="px-4 py-5 my-5 text-center" style="margin-top: 0">
    <h1 class="display-5 fw-bold">Turmas</h1>
</div>

<table class="table table-sm" align="center" style="width: 900px; max-width: 900px">
    <thead>
        <th style="float: left; border: none; margin-bottom: 20px">
            <a href="criar_turma">
                <button type="button" class="btn btn-primary">Nova Turma</button>
            </a>
        </th>
    </thead>
    <thead>
        <tr>
            <th scope="col">Descrição</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for row in turmasData %}
        <tr>
            <td id="td1" scope="col">
                Turma {{ row.descricao }}
            </td>
            <th id="table-button" class="table-button" scope="col">
                <a href="{{url_for('views.eliminar_turma', id=row.id)}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path
                            d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                    </svg>
                </a>
            </th>
            <th id="table-button" class="table-button" scope="col">
                <a href="{{url_for('views.editar_turma', id=row.id)}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path
                            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd"
                            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                    </svg>
                </a>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}